### ISSUE TITLE
Paso 1. Renombrar el repositorio 

### ISSUE THREAD

**Issue by mirenbz** [olatzbalda/olatzbalda.github.io#6]
Vamos a configurar este repositorio para que funcione como vuestra página personal en GitHub y sirva como portafolio del trabajo individual que hacéis en la asignatura Proyectos para la web. Para esto, lo primero es renombrar el repositorio.

Accede a la pestaña **Settings** y en "Repository name", cambia el nombre a:

```
olatzbalda.github.io
```

y haz clic en **Rename**.

Una vez lo hayas hecho, mencióname en un comentario para que lo revise y continuemos con los siguientes pasos.

**Comment by olatzbalda** [comment]
@mberasategi

**Comment by mirenbz** [comment]
¡Bien! Ahora puedes acceder a tu portafolio desde http://olatzbalda.github.io

Continúa con el paso 2 en #7
